%% Robotics System Assignment 4 Matlab Code

%   The University of Melbourne
%   MCEN90028 ROBOTICS SYSTEMS
%   GROUP 3
%   Written by: Hai Dang Nguyen


% this function return the start and end square on the board, as indicating
% in table 1 of the asm4

function Square = listOfMove(i)

list = [['e2','e4'];...
          ['g1','f3'];...
          ['f1','b5'];...
          ['b1','c3'];...
          ['e1','g1'];...
          ['h1','f1'];...
          ['e4','d5'];...
          ['d5','cp'];...
          ['c3','d5'];...
          ['d5','cp'];...
          ['b5','c6'];...
          ['c2','c3'];...
          ['f3','g5'];...
          ['d2','d4'];...
          ['d1','f3'];...
          ['f3','d5'];...
          ['c1','cp'];...
          ['a1','c1'];...
          ['d5','cp'];...
          ['g1','h1'];...
          ['f2','f4'];...
          ['g5','h3'];...
          ['g2','g3'];...
          ['c1','d1'];...
          ['f1','e1']];
      
Square.startSq = list(i,1:2);
Square.endSq = list(i,3:4);

end